name: TinyGo
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  tinygo:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            go-version: "1.18.x"
            tinygo: "0.24.0"
          - platform: ubuntu-latest
            go-version: "1.20.x"
            tinygo: "0.28.0"
    env:
      GO111MODULE: on
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ matrix.tinygo }}
      - name: Test
        run: tinygo test .
